// <auto-generated />
namespace LTQLWEB3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updatetableHOADON : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatetableHOADON));
        
        string IMigrationMetadata.Id
        {
            get { return "202012170603520_update-table-HOADON"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
